### ISSUE TITLE
Make it into userscript

### ISSUE THREAD

**Issue by dichter** [branbarh/Trello-Colors-Extension#2]
Would you consider turning it into an userscript for tampermonkey (and other userscript managers)?
That way the script could be automatically updated, whenever there is a need for change.
No need to switch on the developer mode for extension install. 
And it would work in all browsers, including Firefox, Edge, Opera and Vivaldi, and, of course, still work in Chrome and related browsers.

**Comment by branbarh** [comment]
@dichter I'm new to Tampermonkey, but I believe I figured it out:
[https://greasyfork.org/en/scripts/416394-trello-colors/code](https://greasyfork.org/en/scripts/416394-trello-colors/code)

According to [https://www.tampermonkey.net/scripts.php](https://www.tampermonkey.net/scripts.php), I should be able to sync the script to GitHub; any idea how to do this?

**Comment by dichter** [comment]
Yes, 
you go to "import script" menu https://greasyfork.org/en/import and give it the raw URL from github (make sure to include the branch name, rather then a specific commit name, as only the branch one will ever see any changes). you then can configure a webhook that would push the script over to greasyfork everytime there is a change - https://greasyfork.org/en/users/webhook-info

**Comment by branbarh** [comment]
Four years later, and I finally have the userscript set up, with webhook integration! Recently moved over to a Firefox-based browser, so I figured I'd finally update this.

See commits 076727f and 169db68; the userscript is available on [GreasyFork](https://greasyfork.org/en/scripts/505507-trello-colors).
