### ISSUE TITLE
Google Chrome Display Issue

### ISSUE THREAD

**Issue by firefancy** [branbarh/Trello-Colors-Extension#3]
Hi

I'm using Google Chrome for Windows desktop, version: 90.0.4430.72
And my Windows 10 home os build is: 19042.928

The custom colors for labels works when you're viewing all your lists and have labels showing. But when you select the Edit pencil icon and click "Edit Labels," the custom colors don't show up properly in the menu.

![Screenshot (1162)](https://user-images.githubusercontent.com/46469395/115320209-e86d2780-a12d-11eb-9493-1760ce3e8db5.png)

**Comment by branbarh** [comment]
That merge should have fixed the issue, I’ll check it when I get home.

I’ll leave this open until then.

**Comment by branbarh** [comment]
This has been resolved with the v2 update.
