### ISSUE TITLE
Custom Colors In Colorblind Mode

### ISSUE THREAD

**Issue by vlopezjr** [branbarh/Trello-Colors-Extension#6]
The custom colors in colorblind mode hide the visual cues.  Here is an image with a card that uses Trello colors and another with custom colors using the extension.

![image](https://github.com/user-attachments/assets/099357b9-2647-4d49-bf41-4e3286c95230)

**Comment by branbarh** [comment]
Should be fixed by b932677!

Let me know if you're still having issues.

**Comment by vlopezjr** [comment]
This is great, quick turnaround too.  Really appreciate it.
